# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       이해온의 트래블로그
email:       'haeon.lee.dev@gmail.com'
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         '"https://heaonlee.github.io"' # The base hostname & protocol for your site
youtube:     ''
github:      'https://github.com/haeonlee'
instagram:   'https://www.instagram.com/on_it_book'
linkdin:    'https://www.linkedin.com/in/haeonlee/'

markdown:  kramdown
permalink: pretty
paginate:  60

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
